Playify/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('main/',views.main,name = "main"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]

Playify/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Playify/user/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    path('profile/', views.profile , name = "profile"),
    path('profilesettings/', views.profilesettings , name = "profilesettings"),
    url(r'profile/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile),
    url(r'profile/following/(?P<username>[a-zA-Z0-9]+)$', views.following),
    

]

Playify/templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index'  %}">Playify</a>
        
        <div class="collapse navbar-collapse" id="navbarCollapse">
          
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:articles'  %}">All</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'article:articles'  %}main">Home</a>
          </li>
          </ul>

          <ul class="navbar-nav ml-auto">
          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:dashboard'  %}">{{request.user.username}}</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ HTTP_HOST }}/user/profile/{{article.author.username}}">Profile</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logout'  %}">Logout</a>
          </li>
          {% else %}

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:login'  %}">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register'  %}">Sign In</a>
          </li>
          {% endif %}
          
          
          </ul>
        </div>
    
    
</nav>