Playify/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('main/',views.main,name = "main"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]

Playify/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Playify/article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Username ")
    title = models.CharField(max_length = 50,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Creating Time")
    article_image = models.FileField(blank = True,null = True,verbose_name = "Add Image")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Post",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "Name")
    comment_content = models.CharField(max_length = 200,verbose_name = "Comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

    

Playify/article/forms.py
from django import forms
from .models import Article


class LoginForm(forms.Form):
    username = forms.CharField(label = "User Name")
    password = forms.CharField(label = "Password", widget = forms.PasswordInput)
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

Playify/article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    loggeduser = request.user
    if not loggeduser.is_authenticated:
        return render(request,"404.html")
    keyword = request.GET.get("keyword")
    user = request.user
    following = [user for user in user.profile.following.filter()]
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles,"following":following})


def main(request):
    loggeduser = request.user
    if not loggeduser.is_authenticated:
        return render(request,"404.html")
    keyword = request.GET.get("keyword")
    user = request.user
    following = [user for user in user.profile.following.filter()]
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"main.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"main.html",{"articles":articles,"following":following})

def index(request):
    return render(request,"index.html")
    
def about(request):
    return render(request,"about.html")


@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Post Shared Successfully")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})
def detail(request,id):
    #article = Article.objects.filter(id = id).first()   
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Post Edited Successfully")
        return redirect("article:dashboard")


    return render(request,"update.html",{"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Post Deleted Successfully")

    return redirect("article:dashboard")
def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.user.username
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))
    

Playify/templates/about.html
{% extends "layout.html" %}


{% block body %}

<h3>About Us</h3>
<hr>
        Playify is a social media for gamers.
<p>
        
</p>
{% endblock body %}

Playify/templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Post</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Share Post</button>
        </form>
    </div>
  </div>


{% endblock body %}

Playify/templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class ="row">
    
       
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">
      <img class="rounded-circle account-img" width="50" height="50" src="{{ article.author.profile.image.url }}">
      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
         <a href="../user/profile/{{article.author.username}}">{{article.author.username}}</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Read All</a>
      <hr>
         
        </div>
      </div>
      </div>
{% endfor %}



{% endif %}

{% endblock body %}

Playify/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>{{request.user.username}}</h3>
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Create Post </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Date</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Edit</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Delete</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    No post shared yet...

</div>
{% endif %}



{% endblock body %}


Playify/templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}}
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>

      <h4>Comments</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_content}}<br>
            {{comment.comment_date}} <br>
            
          </div>
        </div>
      {% endfor %}
      
      
      
      {% endif %}

      {% if request.user.is_authenticated %}
      <div class="card my-4">
          <h5 class="card-header">Add Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Add</button>
            </form>
          </div>
        </div>
        </div>
        
      </div>
                {% endif %}


      

{% endblock body %}

Playify/templates/following.html
{% extends "layout.html" %}

{% block body %}



<p>
    {{ n }} following <br>    
    {% if following %}

        {% for user in following %}
        <img class="rounded-circle account-img" width="30" height="30" src="{{ user.profile.image.url }}"> <a href="../{{ user.username }}">{{ user.username }}</a><br>
        
        {% endfor %}
        
        
        
        {% endif %}
        {{ followers.count }} followers <br>
        {% if followers %}
        {% for user in followers %}
        
        <img class="rounded-circle account-img" width="30" height="30" src="{{ user.image.url }}"> 
        <a href="../{{ user.user.username }}">{{ user.user.username }}</a>
        {% endfor %}
        
        
        
        {% endif %}
        
      

</p>
{% endblock body %}

Playify/templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
        <h3>Playify</h3>
        <p></p>
</div>


<p>
        {% if request.user.is_authenticated %}
                Login Succesfully, {{request.user.username}}
        {% endif %}

</p>
{% endblock body %}


Playify/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Playify</title>
</head>
<body>  
        {% include "includes/navbar.html" %}

        

        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
                
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
            {% block body %}
            
            {% endblock body %}

        </div>
    

      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  
    </body>
</html>

Playify/templates/main.html
{% extends "layout.html" %}

{% block body %}

<div class ="row">
    
       
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
{% if article.author in following %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">
      <img class="rounded-circle account-img" width="50" height="50" src="{{ article.author.profile.image.url }}">
      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
         <a href="{{ HTTP_HOST }}/user/profile/{{article.author.username}}">{{article.author.username}}</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Read All</a>
      <hr>
         
        </div>
      </div>
      </div>
      {% endif %}
{% endfor %}



{% endif %}

{% endblock body %}

Playify/templates/profile.html
{% extends "layout.html" %}
{% block body %}

<div class="content-section">
    <div class="media">
      <div class="media-body">
        
        <img class="rounded-circle account-img" width="150" height="150" src="{{ user.profile.image.url }}">
        <h2 class="account-heading">Username: {{ user.username }}</h2>
        <h2 class="account-heading">Status: {{ user.profile.status }}</h2>
        <p class="text-secondary">{{ user.profile }}</p>
      </div>
    </div>
    <!-- FORM HERE -->
  </div>

{% endblock body %}

Playify/templates/profilesettings.html
{% extends "layout.html" %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Profile Settings</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
             {% csrf_token %}

                    {{u_form.as_p}}
                    {{p_form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Save settings</button>
        </form>
    </div>
  </div>

{% endblock body %}

Playify/templates/register.html
{% extends "layout.html" %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Sign In</h3>
        <hr>
        <form method = "post">
             {% csrf_token %}

            {{form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Sign In</button>
        </form>
    </div>
  </div>

{% endblock body %}


Playify/templates/update.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Edit Your Post</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Edit Your Post</button>
        </form>
    </div>
  </div>


{% endblock body %}

Playify/templates/user_profile.html
{% extends "layout.html" %}
{% block body %}

<div class="content-section">
    <div class="media">
      <div class="media-body">
        
        <img class="rounded-circle account-img" width="150" height="150" src="{{ user.profile.image.url }}">
        <h2 class="account-heading">Username: {{ user.username }}</h2>
        <h2 class="account-heading">Status: {{ user.profile.status }}</h2><br>
        <a href="./following/{{user.username}}"><h2 class="mt-4">{{user.following.count}} followers</h2></a>
          <form method = "post" data-="{{ user.username }}">
              {% csrf_token %}
              {% if isSame %}
              <a href="../profilesettings" class="btn btn-primary">Profile settings</a>
              {% else %}


              <br>
              
                
                {% if follow %} 
                  <button id="button1" onclick="document.getElementById('button1')='a'" type = "submit" class = "btn btn-danger">Unfollow</button>
                  {% else %}
                  <button id="button2" onclick="document.getElementById('button2')='b'" type = "submit" class = "btn btn-primary">Follow</button>
                  {% endif %}</button>


              {% endif %}
              
              
        <h2 class="account-heading">User posts:</h2>
          {% if articles %}

{% for article in articles %}

    <!-- Post Content Column -->
    <div class="col-lg-13">
      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
         <a href="../user/profile/{{article.author.username}}">{{article.author.username}}</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Read All</a>
      <hr>
         
        </div>
      
{% endfor %}



{% endif %}
        </p>
        
      </div>
    </div>
  </div>

{% endblock body %}